services:
  Steven\AutoFixturesBundle\Annotations\FixturesAnnotationReader:
    class: Steven\AutoFixturesBundle\Annotations\FixturesAnnotationReader
    arguments: ['@annotation_reader']

  steven_auto_fixtures.command.create_fixtures_command:
    class: Steven\AutoFixturesBundle\Command\CreateFixturesCommand
    arguments: ['@?', '@Steven\AutoFixturesBundle\Services\FixtureManager', '@Doctrine\ORM\EntityManagerInterface']
    tags:
      - { name: console.command }


  steven_auto_fixtures.services.fixturables_classes:
    class: Steven\AutoFixturesBundle\Services\FixturablesClasses
    arguments: ['@symfony.component.finder.finder', '@parameter_bag']

  symfony.component.finder.finder:
    class: Symfony\Component\Finder\Finder

  Steven\AutoFixturesBundle\Services\FixtureManager:
    class: Steven\AutoFixturesBundle\Services\FixtureManager
    arguments:
      - '@steven_auto_fixtures.services.fixturables_classes'
      - '@Steven\AutoFixturesBundle\Annotations\FixturesAnnotationReader'
      - '%fixtures.number_per_entity%'
      - '%fixtures.number_word_text%'
      - '%fixtures.number_word_title%'
      - '%fixtures.language%'
      - '@Doctrine\ORM\EntityManagerInterface'
      - '@steven_auto_fixtures.services.fixture_creator'

  faker.generator:
    class: Faker\Generator

  steven_auto_fixtures.services.fixture_creator:
    class: Steven\AutoFixturesBundle\Services\FixtureCreator
    arguments:
      ['%fixtures.language%']
